on:
  push:
    branches: [ main ]

name: deploy to aws with docker

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build lambda image
        run: sam build --parameter-overrides ImageTag=$GITHUB_SHA BucketName=$BUCKET_NAME --use-container
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Deploy lambda
        run: sam deploy --role-arn $CF_ROLE_ARN --no-confirm-changeset --parameter-overrides ImageTag=$GITHUB_SHA BucketName=$BUCKET_NAME --image-repository $ECR_REPOSITORY
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          CF_ROLE_ARN: ${{ secrets.CF_ROLE_ARN }}
        